### ISSUE TITLE
Hot Seat Mode?

### ISSUE THREAD

**Issue by SevHub** [argosopentech/Conquest#1]
Hi, 

i really like this project as it is open souce and allows me to study how other people create such a game on godot. What I miss is a simple Hot-seat mode, which allows me to test the game without the need of a second client, network traffic etc. From the gameplay video you posted as an example it seams the game was once a hot-seat game. Any chance you bring back this feature?

**Comment by PJ-Finlay** [comment]
I agree this would be a nice feature. I'm not actively developing the game currently but would accept a change if anyone's interested in making it.

**Comment by PJ-Finlay** [comment]
Offline mode is now supported
