### ISSUE TITLE
Sometimes different teams will have the same color

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/Conquest#5]
I think the team colors are selected randomly so sometimes with multiple players two players will have the same color.

**Comment by wamiqurrehman093** [comment]
I check it soon InshaAllah =)

**Comment by wamiqurrehman093** [comment]
It is fixed it now I think and I have provided fix releases for both the game and the server exports. These files should be replaced on the http://conquestgame.online/ web game and the server in the back for the changes to appear.
