### ISSUE TITLE
East Africa not connected to Middle East

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/Conquest#6]
I think there's a bug where you can't fortify through the East Africa - Middle East connection. You can attack correctly but not fortify.

**Comment by argosopentech** [comment]
I think the bug is that it's only connected M.E. -> E. Africa but not the other direction

**Comment by wamiqurrehman093** [comment]
I have fixed it in the latest commit.

**Comment by wamiqurrehman093** [comment]
Now it should work = )

**Comment by PJ-Finlay** [comment]
Awesome thanks!
